export const REGISTER_USERS_REQUEST = "REGISTER_USERS_REQUEST"
export const REGISTER_USERS_SUCCESS = "REGISTER_USERS_SUCCESS"
export const REGISTER_USERS_FAILURE = "REGISTER_USERS_FAILURE"

export const LOGIN_USER_REQUEST = "LOGIN_USER_REQUEST"
export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS"
export const LOGIN_USER_FAILURE = "LOGIN_USER_FAILURE"

export const LOGOUT_USER = "LOGOUT_USER"