export const REGISTER_USERS_REQUEST = "REGISTER_USERS_REQUEST"
export const REGISTER_USERS_SUCCESS = "REGISTER_USERS_SUCCESS"
export const REGISTER_USERS_FAILURE = "REGISTER_USERS_FAILURE"

export const LOGIN_USER_REQUEST = "LOGIN_USER_REQUEST"
export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS"
export const LOGIN_USER_FAILURE = "LOGIN_USER_FAILURE"

export const ADD_TRANSACTION_REQUEST = "ADD_TRANSACTION_REQUEST"
export const ADD_TRANSACTION_SUCCESS = "ADD_TRANSACTION_SUCCESS"
export const ADD_TRANSACTION_FAILURE = "ADD_TRANSACTION_FAILURE"

export const GET_TRANSACTIONS_REQUEST = "GET_TRANSACTIONS_REQUEST"
export const GET_TRANSACTIONS_SUCCESS = "GET_TRANSACTIONS_SUCCESS"
export const GET_TRANSACTIONS_FAILURE = "GET_TRANSACTIONS_FAILURE"

export const GET_TOP_TRANSACTIONS_REQUEST = "GET_TOP_TRANSACTIONS_REQUEST"
export const GET_TOP_TRANSACTIONS_SUCCESS = "GET_TOP_TRANSACTIONS_SUCCESS"
export const GET_TOP_TRANSACTIONS_FAILURE = "GET_TOP_TRANSACTIONS_FAILURE"

export const UPDATE_TRANSACTION_REQUEST = "DELETE_TRANSACTION_REQUEST"
export const UPDATE_TRANSACTION_SUCCESS = "DELETE_TRANSACTION_SUCCESS"
export const UPDATE_TRANSACTION_FAILURE = "DELETE_TRANSACTION_FAILURE"

export const DELETE_TRANSACTIONS_REQUEST = "UPDATE_TRANSACTIONS_REQUEST"
export const DELETE_TRANSACTIONS_SUCCESS = "UPDATE_TRANSACTIONS_SUCCESS"
export const DELETE_TRANSACTIONS_FAILURE = "UPDATE_TRANSACTIONS_FAILURE"

export const FILTER_TRANSACTIONS = "FILTER_TRANSACTIONS"
export const SORT_TRANSACTIONS = "SORT_TRANSACTIONS"

export const REMOVE_MESSAGE = "REMOVE_MESSAGE"

export const LOGOUT_USER = "LOGOUT_USER"